import { NextResponse } from 'next/server';

const tiles = [
    {
        id: 13,
        name: "Marble Polished Floor",
        slug: "marble-polished-floor",
        textureUrl: "/textures/close-up-marble-textured-wall.jpg",
        price: 72.00,
        category: "Floors",
        size: "60x120cm",
        finish: "Polished",
        material: "Marble",
    },
    {
        id: 7,
        name: "Natural Stone Mosaic Floor",
        slug: "natural-stone-mosaic",
        textureUrl: "/images/tile-4.jpg",
        price: 48.00,
        category: "Floors",
        size: "30x30cm",
        finish: "Matt",
        material: "Stone",
    },
    {
        id: 15,
        name: "Diagonal White Marble Tile",
        slug: "diagonal-white-marble-tile",
        textureUrl: "/textures/diagonal-marble-2000-mm.png",
        price: 79.00,
        category: "Floors",
        size: "200x200cm",
        finish: "Polished",
        material: "Marble",
    },
    {
        id: 16,
        name: "White Oiled Timber Floor",
        slug: "white-oiled-timber-floor",
        textureUrl: "/textures/white-oiled-timber-3200-mm.png",
        price: 69.00,
        category: "Floors",
        size: "320x320cm",
        finish: "Oiled",
        material: "Wood",
    },
    {
        id: 17,
        name: "Oak Veneered MDF Floor",
        slug: "oak-veneered-mdf-floor",
        textureUrl: "/textures/oak-veneered-mdf-550-mm.png",
        price: 64.00,
        category: "Floors",
        size: "55x55cm",
        finish: "Veneered",
        material: "Wood",
    },
    {
        id: 19,
        name: "Geometric Line Cream Tile",
        slug: "geometric-line-cream-tile",
        textureUrl: "/textures/geometric-line-cream.png",
        price: 66.00,
        category: "Floors",
        size: "60x60cm",
        finish: "Matt",
        material: "Ceramic",
    },
    {
        id: 20,
        name: "Travertine",
        slug: "travertine-stone-tile",
        textureUrl: "/textures/515.png",
        price: 66.00,
        category: "Floors",
        size: "60x60cm",
        finish: "Matt",
        material: "Ceramic",
    },
    {
        id: 21,
        name: "Travertine",
        slug: "travertine-stone-tile",
        textureUrl: "/textures/travertine-2000-mm-architextures.webp",
        price: 66.00,
        category: "Floors",
        size: "60x60cm",
        finish: "Matt",
        material: "Ceramic",
    },
    {
        id: 22,
        name: "Travertine",
        slug: "travertine-stone-tile",
        textureUrl: "/textures/image.png",
        price: 66.00,
        category: "Floors",
        size: "60x60cm",
        finish: "Matt",
        material: "Ceramic",
    },
    {
        id: 23,
        name: "Travertine",
        slug: "travertine-stone-tile",
        textureUrl:"/textures/drag-textured-plaster-1499-mm-architextures.jpg",
        price: 66.00,
        category: "Floors",
        size: "60x60cm",
        finish: "Matt",
        material: "Ceramic",
    },

];

export async function GET() {
    return NextResponse.json(tiles);
}
